name: slc6env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10        # RDKit is most stable on Python 3.10
  - numpy<2.0
  - rdkit=2023.09.1    # stable RDKit release compatible with numpy<2
  - openbabel
  - autodock-vina
  - fpocket
  - pip
  - pandas
  - biopython
  - matplotlib
  - jupyter
  - mgltools
  - bioconda
  - pip:
      - meeko
