#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Docking script using AutoDock Vina with parallelization
"""

import os
import argparse
import subprocess
from glob import glob
import numpy as np
import csv
import shutil
from multiprocessing import Pool, cpu_count


# =========================
#   POCKET TOOLS
# =========================

def get_top_pocket_pairs(csv_file, top_n=5):
    """
    Reads a CSV file containing pocket similarity scores and returns the top N pocket pairs.

    Parameters :
    ------------
    csv_file : str
        The file path to the CSV file generated by pocket_scoring.py
    top_n : int, optional
        The number of top pocket pairs to return (default is 5)

    Returns :
    ---------
    list[dict]
        A list of dictionaries, each containing information about a pocket pair.
        Each dictionary has the following keys:
        - 'template_pocket' : str
            Identifier of the template pocket
        - 'target_pocket' : str  
            Identifier of the target pocket
        - 'template_residues' : list[int]
            List of residue numbers for the template pocket
        - 'target_residues' : list[int]
            List of residue numbers for the target pocket
        - 'SO' : float
            Geometric overlap score between template and target positive pockets (0.0 to 1.0, higher = better)
        - 'SC' : float
            Compatibility score of the target pocket with target's negative pockets (0.0 to 1.0, lower = better)
        - 'global_score' : float
            Combined similarity score SO*(1-SC), higher = better

    Note :
    ------
    The CSV file is assumed to be pre-sorted by global_score in descending order.
    Only the first top_n entries are returned without re-sorting.
    """
    pairs = []
    with open(csv_file, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            template_res = [int(r) for r in row["template_residues"].split(",") if r]
            target_res   = [int(r) for r in row["target_residues"].split(",") if r]

            pairs.append({
                "template_pocket": row["template_pocket"],
                "target_pocket": row["target_pocket"],
                "template_residues": template_res,
                "target_residues": target_res,
                "SO": float(row["SO"]),
                "SC": float(row["SC"]),
                "global_score": float(row["global_score"])
            })

    return pairs[:top_n]


def pocket_from_residues(pdb_file, residues, padding=3.0):
    """
    Extracts a binding pocket from a PDB file based on specified residues and calculates its bounding box.

    Parameters :
    ------------
    pdb_file : str
        Path to the PDB file containing the protein structure
    residues : list[int]
        List of residue numbers that define the pocket of interest
    padding : float, optional
        Additional space (in Angstroms) to add around the pocket's bounding box (default is 3.0 Å)

    Returns :
    ---------
    tuple
        A tuple containing two elements:
        - center : tuple[float, float, float]
            The geometric center of the pocket (x, y, z coordinates in Angstroms)
        - size : tuple[float, float, float]
            The dimensions of the bounding box (width, height, depth in Angstroms)
            with padding applied to each dimension

    Raises :
    --------
    ValueError
        If no atoms are found for any of the specified residues in the PDB file

    Notes :
    -------
    - Only ATOM and HETATM records are considered from the PDB file
    - The bounding box is axis-aligned (aligned with coordinate axes)
    - Padding is applied uniformly to all three dimensions
    - Residue numbers should match those in the PDB file's residue numbering scheme
    """
    coords = []
    with open(pdb_file, "r") as pdb:
        for line in pdb:
            if line.startswith(("ATOM", "HETATM")):
                res_id = int(line[22:26].strip())
                if res_id in residues:
                    x = float(line[30:38])
                    y = float(line[38:46])
                    z = float(line[46:54])
                    coords.append([x, y, z])

    if not coords:
        raise ValueError("No atoms found for these residues.")

    coords = np.array(coords)
    min_c = coords.min(axis=0)
    max_c = coords.max(axis=0)
    center = tuple((min_c + max_c) / 2)
    size = tuple((max_c - min_c) + padding)
    return center, size


# =========================
#   PREPARE RECEPTOR
# =========================

def prepare_receptor(pdb_file, output_dir, prepare_receptor_script):
    """
    Converts a PDB protein file to PDBQT format using AutoDockTools' prepare_receptor script.

    Parameters :
    ------------
    pdb_file : str
        Path to the input PDB file containing the receptor structure
    output_dir : str
        Directory where the output PDBQT file will be saved
    prepare_receptor_script : str
        Path to the AutoDockTools prepare_receptor.py script

    Returns :
    ---------
    str
        Absolute path to the generated PDBQT file

    Raises :
    --------
    subprocess.CalledProcessError
        If the prepare_receptor.py script fails to execute successfully
    FileNotFoundError
        If the input PDB file or prepare_receptor_script doesn't exist

    Notes :
    -------
    - This is a prerequisite step for molecular docking with AutoDock Vina
    - Requires Python 2 to run the prepare_receptor.py script
    - Automatically adds hydrogens to the receptor structure
    """
    os.makedirs(output_dir, exist_ok=True)
    pdbqt = os.path.join(output_dir, os.path.basename(pdb_file).replace(".pdb", ".pdbqt"))

    cmd = [
        "python2",
        prepare_receptor_script,
        "-r", os.path.abspath(pdb_file),
        "-o", os.path.abspath(pdbqt),
        "-A", "hydrogens"
    ]
    subprocess.check_call(cmd)

    return os.path.abspath(pdbqt)


# =========================
#       DOCKING
# =========================

def run_vina(receptor_pdbqt, ligand_pdbqt, center, size, output_dir, exhaustiveness=8):
    """
    Performs molecular docking using AutoDock Vina with specified search parameters.

    Parameters :
    ------------
    receptor_pdbqt : str
        Path to the receptor file in PDBQT format
    ligand_pdbqt : str
        Path to the ligand file in PDBQT format
    center : tuple[float, float, float]
        Coordinates (x, y, z in Angstroms) defining the center of the search box
    size : tuple[float, float, float]
        Dimensions (x, y, z in Angstroms) defining the search box size
    output_dir : str
        Directory where docking results will be saved
    exhaustiveness : int, optional
        Exhaustiveness of the global search (higher = more thorough but slower)
        (default is 8)

    Returns :
    ---------
    str
        Path to the output PDBQT file containing docking poses

    Raises :
    --------
    subprocess.CalledProcessError
        If the Vina docking process fails to execute successfully
    FileNotFoundError
        If receptor_pdbqt, ligand_pdbqt, or the vina executable is not found

    Notes :
    -------
    - Higher exhaustiveness values improve search quality but increase computation time
    - For protein-ligand docking, typical exhaustiveness values range from 8 to 32
    """
    os.makedirs(output_dir, exist_ok=True)
    out_pdbqt = os.path.join(output_dir, "out.pdbqt")

    cmd = [
        "vina",
        "--receptor", receptor_pdbqt,
        "--ligand", ligand_pdbqt,
        "--center_x", str(center[0]),
        "--center_y", str(center[1]),
        "--center_z", str(center[2]),
        "--size_x", str(size[0]),
        "--size_y", str(size[1]),
        "--size_z", str(size[2]),
        "--exhaustiveness", str(exhaustiveness),
        "--out", out_pdbqt,
    ]

    subprocess.run(cmd, check=True)
    return out_pdbqt


def parse_vina_score_from_pdbqt(pdbqt_file):
    """
    Extracts the Vina docking score from a PDBQT result file.

    Parameters :
    ------------
    pdbqt_file : str
        Path to the PDBQT file generated by AutoDock Vina docking

    Returns :
    ---------
    float or None
        The docking score (affinity in kcal/mol) if found in the file,
        None if no score line is found in the file

    Notes :
    -------
    - Negative scores indicate favorable binding (more negative = stronger binding)
    - Typical scores range from -15 (very strong) to 0 (very weak) kcal/mol
    """
    with open(pdbqt_file) as f:
        for line in f:
            if line.startswith("REMARK VINA RESULT"):
                return float(line.split()[3])
    return None


# =========================
#   PARALLEL WORKER
# =========================

def vina_worker(args):
    """
    Worker function for parallel docking execution of a single ligand.

    Parameters :
    ------------
    args : tuple
        A tuple containing the following elements in order:
        - ligand_pdbqt : str
            Path to the ligand file in PDBQT format
        - receptor_pdbqt : str
            Path to the receptor file in PDBQT format
        - center : tuple[float, float, float]
            Coordinates (x, y, z) defining the center of the docking search box
        - size : tuple[float, float, float]
            Dimensions (x, y, z) defining the size of the docking search box
        - output_root : str
            Root directory where output subdirectories will be created

    Returns :
    ---------
    dict or None
        A dictionary containing docking results if successful, None if failed.
        The dictionary has the following keys:
        - 'ligand' : str
            Name of the ligand (derived from input filename without extension)
        - 'score' : float
            Docking score (affinity in kcal/mol) from Vina
        - 'pdbqt' : str
            Path to the output PDBQT file with docking poses

    Notes :
    -------
    - This function is designed to be used with multiprocessing/map functions
    - Each ligand gets its own output directory: {output_root}/{ligand_name}/docking/
    - Returns None if any exception occurs during docking or score parsing
    - Only captures the first docking score if multiple poses are generated
    """
    ligand_pdbqt, receptor_pdbqt, center, size, output_root = args
    ligand_name = os.path.splitext(os.path.basename(ligand_pdbqt))[0]

    ligand_out_dir = os.path.join(output_root, ligand_name, "docking")
    try:
        out_pdbqt = run_vina(
            receptor_pdbqt,
            ligand_pdbqt,
            center,
            size,
            ligand_out_dir
        )
        score = parse_vina_score_from_pdbqt(out_pdbqt)
        return {
            "ligand": ligand_name,
            "score": score,
            "pdbqt": out_pdbqt
        }
    except Exception as e:
        print(f"[ERROR] {ligand_name}: {e}")
        return None


# =========================
#  DOCK ALL LIGANDS
# =========================

def dock_one_pocket_all_ligands(receptor_pdb, ligands_dir, pocket_residues,
                                output_dir, prepare_receptor_script, n_cpu,
                                pocket_index=None, total_pockets=None):
    """
    Performs docking of multiple ligands against a single protein pocket in parallel.

    Parameters :
    ------------
    receptor_pdb : str
        Path to the receptor protein structure in PDB format
    ligands_dir : str
        Directory containing ligand files in PDBQT format
    pocket_residues : list[int]
        List of residue numbers defining the binding pocket
    output_dir : str
        Directory where all docking results will be stored
    prepare_receptor_script : str
        Path to AutoDockTools' prepare_receptor.py script
    n_cpu : int
        Number of CPU cores to use for parallel docking
    pocket_index : int, optional
        Index of this pocket (for progress tracking)
    total_pockets : int, optional
        Total number of pockets being processed (for progress tracking)

    Returns :
    ---------
    list[dict]
        List of docking results, where each dictionary contains:
        - 'ligand' : str - Ligand name
        - 'score' : float - Docking score (affinity in kcal/mol)
        - 'pdbqt' : str - Path to output PDBQT file with docking poses

    Notes :
    -------
    - The function performs these main steps:
    1. Calculates docking search box from pocket residues
    2. Prepares receptor PDBQT file (once for all ligands)
    3. Discovers all PDBQT ligands in the ligands directory
    4. Runs docking in parallel using multiprocessing.Pool
    5. Tracks progress with real-time console output
    """
    pocket_name = os.path.basename(output_dir)

    # 1) Pocket box
    center, size = pocket_from_residues(receptor_pdb, pocket_residues)
    print(f"\n=== POCKET {pocket_index}/{total_pockets} : {pocket_name} ===")
    print(f"Pocket Center: {center}, Size: {size}")

    # 2) Prepare receptor once
    receptor_pdbqt = prepare_receptor(
        receptor_pdb,
        os.path.join(output_dir, "receptor"),
        prepare_receptor_script
    )

    # 3) Ligands list
    ligands = glob(os.path.join(ligands_dir, "*.pdbqt"))
    n_lig = len(ligands)
    print(f"Docking {n_lig} ligands using {n_cpu} CPUs…")

    jobs = [
        (os.path.abspath(lig), receptor_pdbqt, center, size, output_dir)
        for lig in ligands
    ]

    # 4) Parallel execution WITH PROGRESS COUNTER
    results = []
    done = 0
    with Pool(n_cpu) as pool:
        for res in pool.imap_unordered(vina_worker, jobs):
            done += 1
            if res:
                results.append(res)
            if res:
                print(
                    f"[Pocket {pocket_index}] Ligand {done}/{n_lig}: {res['ligand']}  Score={res['score']}",
                    flush = True
                    )
            else:
                print(
                    f"[Pocket {pocket_index}] Ligand {done}/{n_lig}: FAILED",
                    flush = True
                    )

    return results



# =========================
#          MAIN
# =========================

def main():
    """
    Main execution function for comparative docking and selectivity analysis.

    Parameters :
    ------------
    Uses command-line arguments via argparse

    Command-line Arguments :
    ------------------------
    --template_pdb : str (required)
        Path to the template protein structure in PDB format
    --target_pdb : str (required)
        Path to the target protein structure in PDB format
    --ligands : str (required)
        Directory containing ligand files in PDBQT format
    --pocket_scores_csv : str (required)
        CSV file containing pocket similarity scores from pocket_scoring.py
    --out : str (optional, default="docking_results")
        Output directory for all results
    --prep_receptor : str (required)
        Path to AutoDockTools' prepare_receptor.py script
    --cpu : int (optional, default=1)
        Number of CPU cores to use for parallel docking

    Outputs :
    ---------
    1. Creates subdirectories for each pocket pair (template_X/, target_X/)
    2. Generates docking_selectivity_scores.tsv with all docking and selectivity scores
    3. Creates top10_ligands/ directory with PDBQT files for top 10 selective ligands

    Process Flow :
    --------------
    1. Loads top pocket pairs from CSV (using only the top pair by default)
    2. For each pocket pair:
    a. Docks all ligands against template pocket
    b. Docks all ligands against target pocket
    c. Calculates selectivity scores for each ligand
    3. Sorts ligands by selectivity score (highest first)
    4. Saves results and extracts top 10 ligands

    Selectivity Calculation :
    -------------------------
    For each ligand, the selectivity score is computed as:
        selectivity_score = -target_score + 1.0 * (template_score - target_score)
    Where:
        - Higher values indicate better selectivity for target over template
        - Negative target_score indicates strong binding to target
        - (template_score - target_score) measures binding preference

    Notes :
    -------
    - Uses parallel processing for efficient docking of multiple ligands
    - Only processes the top pocket pair (top_n=5 from get_top_pocket_pairs)
    - The weight w=1.0 in selectivity calculation can be adjusted if needed
    """
    parser = argparse.ArgumentParser(description="AutoDock Vina docking (parallel)")

    parser.add_argument("--template_pdb", required=True)
    parser.add_argument("--target_pdb", required=True)
    parser.add_argument("--ligands", required=True)
    parser.add_argument("--pocket_scores_csv", required=True)
    parser.add_argument("--out", default="docking_results")
    parser.add_argument("--prep_receptor", required=True)
    parser.add_argument("--cpu", type=int, default=1, help="Number of CPUs to use")

    args = parser.parse_args()

    print(f"Using {args.cpu} CPUs")

    # 1) Load top pockets
    pocket_pairs = get_top_pocket_pairs(args.pocket_scores_csv, top_n=1)

    # 2) Docking loop
    full_results = []

    for idx, pair in enumerate(pocket_pairs, start=1):
        print(f"\n===== DOCKING POCKET PAIR {idx} =====")

        temp_res = pair["template_residues"]
        targ_res = pair["target_residues"]

        out_dir_template = os.path.join(args.out, f"template_{idx}")
        out_dir_target   = os.path.join(args.out, f"target_{idx}")

        # Template docking
        template_scores = dock_one_pocket_all_ligands(
            args.template_pdb,
            args.ligands,
            temp_res,
            out_dir_template,
            args.prep_receptor,
            args.cpu,
            pocket_index=idx,
            total_pockets=len(pocket_pairs)
        )

        # Target docking
        target_scores = dock_one_pocket_all_ligands(
            args.target_pdb,
            args.ligands,
            targ_res,
            out_dir_target,
            args.prep_receptor,
            args.cpu,
            pocket_index=idx,
            total_pockets=len(pocket_pairs)
        )

        # Merge results
        template_dict = {r["ligand"]: r for r in template_scores}
        target_dict = {r["ligand"]: r for r in target_scores}

        for ligand in template_dict:
            if ligand in target_dict:
                st = template_dict[ligand]["score"]
                sa = target_dict[ligand]["score"]

                # Selectivity score
                w = 1.0
                selectivity_score = -sa + w * (st - sa)

                full_results.append({
                    "ligand": ligand,
                    "score_template": st,
                    "score_target": sa,
                    "selectivity_score": selectivity_score,
                    "pdbqt_target": target_dict[ligand]["pdbqt"],
                    "pdbqt_template": template_dict[ligand]["pdbqt"],
                    "template_pocket": pair["template_pocket"],
                    "target_pocket": pair["target_pocket"]
                })

    # Sort by selectivity
    full_results.sort(key=lambda x: x["selectivity_score"], reverse=True)

    # Write global TSV
    out_tsv = os.path.join(args.out, "docking_selectivity_scores.tsv")
    os.makedirs(args.out, exist_ok=True)

    with open(out_tsv, "w") as f:
        f.write("ligand\tscore_template\tscore_target\tselectivity_score\ttemplate_pocket\ttarget_pocket\n")
        for r in full_results:
            f.write(f"{r['ligand']}\t{r['score_template']}\t{r['score_target']}\t"
                    f"{r['selectivity_score']}\t{r['template_pocket']}\t{r['target_pocket']}\n")

    print(f"\nDOCKING SELECTIVITY SCORES WRITTEN TO: {out_tsv}")

    # Extract top 10
    top10 = full_results[:10]
    top_dir = os.path.join(args.out, "top10_ligands")
    os.makedirs(top_dir, exist_ok=True)

    for r in top10:
        shutil.copy(r["pdbqt_target"], os.path.join(top_dir, f"{r['ligand']}_A20.pdbqt"))
        shutil.copy(r["pdbqt_template"], os.path.join(top_dir, f"{r['ligand']}_A19.pdbqt"))

    print(f"Top 10 ligands written to: {top_dir}")


if __name__ == "__main__":
    main()
